// Copyright (c) 2023 Quetzal Rivera.
// Licensed under the MIT License, See LICENCE in the project root for license information.

namespace Vite.AspNetCore.Abstractions
{
	/// <summary>
	/// Represents a chunk of JavaScript or CSS code generated by Vite.
	/// </summary>
	public interface IViteChunk
	{
		/// <summary>
		/// Gets the file name of the chunk.
		/// </summary>
		string File { get; }
		/// <summary>
		/// The relative src path from project root.
		/// </summary>
		string? Src { get; }
		/// <summary>
		/// True, if the current chunk file is an entrypoint.
		/// </summary>
		bool? IsEntry { get; }
		/// <summary>
		/// List of chunk paths that are imported by the current chunk.
		/// </summary>
		IEnumerable<string>? DynamicImports { get; }
		/// <summary>
		/// List of all CSS files imported by the current chunk.
		/// </summary>
		IEnumerable<string>? Css { get; }
		/// <summary>
		/// List of all assets imported by the current chunk.
		/// </summary>
		IEnumerable<string>? Assets { get; }
		/// <summary>
		/// True, if the current chunk if a dynamic import entrypoint.
		/// </summary>
		bool? IsDynamicEntry { get; }
		/// <summary>
		/// List of all imports.
		/// </summary>
		IEnumerable<string>? Imports { get; }
	}
}
